/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;

/**
 *
 * @author admin pc
 */
public class v_menu_produksi extends javax.swing.JFrame {

    /**
     * Creates new form v_menu_produksi
     */
    public v_menu_produksi() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public JButton getpml_lahan_btn(){
        return pml_lahan_btn;
    }
    public JButton gethsl_produksi_btn(){
        return hsl_produksi_btn;
    }
    public JButton getpenjualan_btn(){
        return penjualan_btn;
    }
    public JButton getk_produksi_btn(){
        return k_produksi_btn;
    }
    public JButton getexit_btn(){
        return exit_btn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pml_lahan_btn = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();
        hsl_produksi_btn = new javax.swing.JButton();
        penjualan_btn = new javax.swing.JButton();
        k_produksi_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pml_lahan_btn.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        pml_lahan_btn.setText("Pemeliharaan Lahan");
        getContentPane().add(pml_lahan_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 280, 50));

        exit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/sipexit.png"))); // NOI18N
        getContentPane().add(exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, 50, 40));

        hsl_produksi_btn.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        hsl_produksi_btn.setText("Hasil Produksi");
        getContentPane().add(hsl_produksi_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 280, 50));

        penjualan_btn.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        penjualan_btn.setText("Penjualan");
        getContentPane().add(penjualan_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 280, 50));

        k_produksi_btn.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        k_produksi_btn.setText("Keputusan Produksi");
        getContentPane().add(k_produksi_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 280, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/beranda.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_menu_produksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_menu_produksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_menu_produksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_menu_produksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_menu_produksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit_btn;
    private javax.swing.JButton hsl_produksi_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton k_produksi_btn;
    private javax.swing.JButton penjualan_btn;
    private javax.swing.JButton pml_lahan_btn;
    // End of variables declaration//GEN-END:variables
}
