/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;

/**
 *
 * @author admin pc
 */
public class v_menu_ramal extends javax.swing.JFrame {

    /**
     * Creates new form v_menu_ramal
     */
    public v_menu_ramal() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public JButton getprd_waktu_btn(){
        return prd_waktu_btn;
    }
    public JButton getjual_garam_btn(){
        return jual_garam_btn;
    }
    public JButton getprd_waktu2_btn(){
        return prd_waktu2_btn;
    }
    public JButton getxy_btn(){
        return xy_btn;
    }
    public JButton getramal_garam_btn(){
        return ramal_garam_btn;
    }
    public JButton getback_btn(){
        return back_btn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jual_garam_btn = new javax.swing.JButton();
        prd_waktu2_btn = new javax.swing.JButton();
        xy_btn = new javax.swing.JButton();
        ramal_garam_btn = new javax.swing.JButton();
        prd_waktu_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jual_garam_btn.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jual_garam_btn.setText("2. Jual Garam");
        getContentPane().add(jual_garam_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 300, 50));

        prd_waktu2_btn.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        prd_waktu2_btn.setText("3. Periode Waktu²");
        getContentPane().add(prd_waktu2_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 300, 50));

        xy_btn.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        xy_btn.setText("4. XY (Waktu * Garam)");
        getContentPane().add(xy_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 300, 50));

        ramal_garam_btn.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        ramal_garam_btn.setText("Ramal Garam");
        getContentPane().add(ramal_garam_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 300, 50));

        prd_waktu_btn.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        prd_waktu_btn.setText("1. Periode Waktu");
        getContentPane().add(prd_waktu_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 300, 50));

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/back.png"))); // NOI18N
        getContentPane().add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/peramalan.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_menu_ramal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_menu_ramal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_menu_ramal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_menu_ramal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_menu_ramal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jual_garam_btn;
    private javax.swing.JButton prd_waktu2_btn;
    private javax.swing.JButton prd_waktu_btn;
    private javax.swing.JButton ramal_garam_btn;
    private javax.swing.JButton xy_btn;
    // End of variables declaration//GEN-END:variables
}
