/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author admin pc
 */
public class v_pml_lahan extends javax.swing.JFrame {

    /**
     * Creates new form v_pml_lahan
     */
    public v_pml_lahan() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public JTextField getid_pml_lahan_tf(){
        return id_pml_lahan_tf;
    }
    public JComboBox getbulan_pml_lahan_combo(){
        return bulan_pml_lahan_combo;
    }
    public JTextField gettahun_pml_lahan_tf(){
        return tahun_pml_lahan_tf;
    }
    public JComboBox getslr_utama_combo(){
        return slr_utama_combo;
    }
    public JComboBox getbozem_combo(){
        return bozem_combo;
    }
    public JComboBox getpintu_air_combo(){
        return pintu_air_combo;
    }
    public JComboBox getphb_evaporator_combo(){
        return phb_evaporator_combo;
    }
    public JComboBox getmeja_kts_combo(){
        return meja_kts_combo;
    }
    public JTable gettabel_pml_lahan(){
        return tabel_pml_lahan;
    }
    public JButton getsimpan_btn(){
        return simpan_btn;
    }
    public JButton getback_btn(){
        return back_btn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pml_lahan = new javax.swing.JTable();
        back_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        bulan_pml_lahan_combo = new javax.swing.JComboBox<>();
        tahun_pml_lahan_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        slr_utama_combo = new javax.swing.JComboBox<>();
        bozem_combo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pintu_air_combo = new javax.swing.JComboBox<>();
        phb_evaporator_combo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        meja_kts_combo = new javax.swing.JComboBox<>();
        simpan_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id_pml_lahan_tf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_pml_lahan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_pml_lahan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 1070, 130));

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/back.png"))); // NOI18N
        getContentPane().add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel10.setText("Bulan                                  :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        bulan_pml_lahan_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        jPanel1.add(bulan_pml_lahan_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));
        jPanel1.add(tahun_pml_lahan_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 130, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel6.setText("Saluran Utama                    :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel5.setText("Tahun                                 :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        slr_utama_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rusak", "Tidak" }));
        jPanel1.add(slr_utama_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 130, 30));

        bozem_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rusak", "Tidak" }));
        jPanel1.add(bozem_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 130, 30));

        jLabel7.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel7.setText("Bozem                                :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel8.setText("Pintu Air                             :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        pintu_air_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rusak", "Tidak" }));
        jPanel1.add(pintu_air_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 130, 30));

        phb_evaporator_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rusak", "Tidak" }));
        jPanel1.add(phb_evaporator_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 130, 30));

        jLabel9.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel9.setText("Penghubung Evaporator     :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel3.setText("Meja Kristalisasi                 :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        meja_kts_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rusak", "Tidak" }));
        jPanel1.add(meja_kts_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 130, 30));

        simpan_btn.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        simpan_btn.setText("Simpan");
        jPanel1.add(simpan_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 730, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pemeliharaanlahan.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel4.setText("Id Pemeliharaan Lahan       :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));
        getContentPane().add(id_pml_lahan_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_pml_lahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_pml_lahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_pml_lahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_pml_lahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_pml_lahan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JComboBox<String> bozem_combo;
    private javax.swing.JComboBox<String> bulan_pml_lahan_combo;
    private javax.swing.JTextField id_pml_lahan_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> meja_kts_combo;
    private javax.swing.JComboBox<String> phb_evaporator_combo;
    private javax.swing.JComboBox<String> pintu_air_combo;
    private javax.swing.JButton simpan_btn;
    private javax.swing.JComboBox<String> slr_utama_combo;
    private javax.swing.JTable tabel_pml_lahan;
    private javax.swing.JTextField tahun_pml_lahan_tf;
    // End of variables declaration//GEN-END:variables
}
